namespace QuotesApi;

/// <summary>Real, well-known, public-domain quotes used only to seed the dev database with
/// realistic-looking data instead of "Quote number N" placeholders.</summary>
public static class SeedQuotes
{
    public static readonly (string Author, string Text)[] RealQuotes =
    [
        ("Mark Twain", "The secret of getting ahead is getting started."),
        ("Mark Twain", "Kindness is the language which the deaf can hear and the blind can see."),
        ("Albert Einstein", "Imagination is more important than knowledge."),
        ("Albert Einstein", "Try not to become a person of success, but rather try to become a person of value."),
        ("Albert Einstein", "Life is like riding a bicycle. To keep your balance, you must keep moving."),
        ("Mahatma Gandhi", "Be the change that you wish to see in the world."),
        ("Mahatma Gandhi", "The weak can never forgive. Forgiveness is the attribute of the strong."),
        ("Abraham Lincoln", "The best way to predict your future is to create it."),
        ("Abraham Lincoln", "Whatever you are, be a good one."),
        ("Winston Churchill", "Success is not final, failure is not fatal: it is the courage to continue that counts."),
        ("Winston Churchill", "Attitude is a little thing that makes a big difference."),
        ("Confucius", "It does not matter how slowly you go as long as you do not stop."),
        ("Confucius", "Our greatest glory is not in never falling, but in rising every time we fall."),
        ("Aristotle", "Knowing yourself is the beginning of all wisdom."),
        ("Aristotle", "We are what we repeatedly do. Excellence, then, is not an act, but a habit."),
        ("Ralph Waldo Emerson", "Do not go where the path may lead, go instead where there is no path and leave a trail."),
        ("Ralph Waldo Emerson", "What lies behind us and what lies before us are tiny matters compared to what lies within us."),
        ("Henry David Thoreau", "Go confidently in the direction of your dreams. Live the life you have imagined."),
        ("Helen Keller", "The best and most beautiful things in the world cannot be seen or even touched."),
        ("Helen Keller", "Alone we can do so little; together we can do so much."),
        ("Eleanor Roosevelt", "The future belongs to those who believe in the beauty of their dreams."),
        ("Eleanor Roosevelt", "No one can make you feel inferior without your consent."),
        ("Benjamin Franklin", "An investment in knowledge pays the best interest."),
        ("Benjamin Franklin", "By failing to prepare, you are preparing to fail."),
        ("Leonardo da Vinci", "Simplicity is the ultimate sophistication."),
        ("Leonardo da Vinci", "Learning never exhausts the mind."),
        ("Charles Darwin", "It is not the strongest of the species that survives, but the most adaptable to change."),
        ("Marie Curie", "Nothing in life is to be feared, it is only to be understood."),
        ("Marie Curie", "One never notices what has been done; one can only see what remains to be done."),
        ("Socrates", "The only true wisdom is in knowing you know nothing."),
        ("Socrates", "An unexamined life is not worth living."),
        ("Plato", "The beginning is the most important part of the work."),
        ("Seneca", "Luck is what happens when preparation meets opportunity."),
        ("Marcus Aurelius", "You have power over your mind, not outside events. Realize this, and you will find strength."),
        ("Jane Austen", "There is nothing I would not do for those who are really my friends."),
        ("Charles Dickens", "No one is useless in this world who lightens the burdens of another."),
        ("Oscar Wilde", "Be yourself; everyone else is already taken."),
        ("Oscar Wilde", "We are all in the gutter, but some of us are looking at the stars."),
        ("Virginia Woolf", "You cannot find peace by avoiding life."),
        ("Frederick Douglass", "Once you learn to read, you will be forever free."),
        ("Harriet Tubman", "Every great dream begins with a dreamer."),
        ("Booker T. Washington", "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome."),
        ("Susan B. Anthony", "Failure is impossible."),
        ("Florence Nightingale", "I attribute my success to this: I never gave or took any excuse."),
        ("Vincent van Gogh", "Great things are done by a series of small things brought together."),
        ("Ludwig van Beethoven", "To play a wrong note is insignificant; to play without passion is inexcusable."),
        ("Johann Wolfgang von Goethe", "Whatever you can do, or dream you can, begin it."),
        ("Friedrich Nietzsche", "He who has a why to live can bear almost any how."),
        ("Sun Tzu", "In the midst of chaos, there is also opportunity."),
        ("Lao Tzu", "A journey of a thousand miles begins with a single step."),
        ("Lao Tzu", "Nature does not hurry, yet everything is accomplished."),
        ("William Shakespeare", "This above all: to thine own self be true."),
        ("Walt Whitman", "Keep your face always toward the sunshine, and shadows will fall behind you."),
        ("Emily Dickinson", "Forever is composed of nows."),
        ("Nikola Tesla", "The present is theirs; the future, for which I really worked, is mine."),
        ("Thomas Edison", "Genius is one percent inspiration and ninety-nine percent perspiration."),
        ("Thomas Edison", "I have not failed. I've just found 10,000 ways that won't work."),
        ("Alexander Graham Bell", "Before anything else, preparation is the key to success."),
        ("Theodore Roosevelt", "Believe you can and you're halfway there."),
        ("Theodore Roosevelt", "Do what you can, with what you have, where you are."),
        ("George Washington", "It is better to offer no excuse than a bad one."),
        ("Louisa May Alcott", "I am not afraid of storms, for I am learning how to sail my ship."),
        ("Anne Frank", "Whoever is happy will make others happy too."),
        ("Anne Frank", "Where there's hope, there's life."),
    ];
}
